title: PC Part Detector
description: Classify Images of PC Parts using Deep Learning!
about:
  This is a deep learning model trained to classify the following categories of common PC Parts
  - CPU's (Central Processing Units)
  - GPU's (Graphics Processing Units)
  - MOBO's (MotherBoards)
  - PSU's (Power Supplies)
  - RAM (RandoM Access Memory)
  - Mouse (Does this need an explanation)
  - Keyboard (This too????)


  The project was built by [Andrew Pynch](https://github.com/andrew-pynch)


  More info and the source code can be found [here](https://github.com/andrew-pynch/pc-part-detector-app)

code: https://github.com/andrew-pynch/pc-part-detector-app

sampleImages:
  - name: GPU
    url: https://i.imgur.com/M6IDlLV.jpg
  - name: CPU
    url: https://i.imgur.com/jiswhrS.jpg
  - name: RAM
    url: https://i.imgur.com/J2v3bGm.jpg
  - name: Mouse
    url: https://i.imgur.com/RBMrVWV.jpg
  - name: Keyboard
    url: https://i.imgur.com/DUA7JT3.jpg
  - name: Computer Case (Untrained PC Part)
    url: https://i.imgur.com/zeo8Sl2.jpg
